/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as MemberRouteRouteImport } from './routes/_member/route'
import { Route as StaffRouteRouteImport } from './routes/_staff/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FindACoachRouteImport } from './routes/find-a-coach'
import { Route as ForCoachesRouteImport } from './routes/for-coaches'
import { Route as ForOrganisationsRouteImport } from './routes/for-organisations'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NoAccessRouteImport } from './routes/no-access'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StaffSignInRouteImport } from './routes/staff-sign-in'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as LocaleFindACoachRouteImport } from './routes/$locale/find-a-coach'
import { Route as LocaleForCoachesRouteImport } from './routes/$locale/for-coaches'
import { Route as LocaleForOrganisationsRouteImport } from './routes/$locale/for-organisations'
import { Route as LocaleImprintRouteImport } from './routes/$locale/imprint'
import { Route as LocaleInsightsRouteImport } from './routes/$locale/insights'
import { Route as LocalePrivacyRouteImport } from './routes/$locale/privacy'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as MemberMyProfileRouteImport } from './routes/_member/my-profile'
import { Route as StaffArticlesRouteImport } from './routes/_staff/articles'
import { Route as StaffCoachFinderRouteImport } from './routes/_staff/coach-finder'
import { Route as StaffIntegrationRouteImport } from './routes/_staff/integration'
import { Route as StaffRolesRouteImport } from './routes/_staff/roles'
import { Route as StaffVocabulariesRouteImport } from './routes/_staff/vocabularies'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ClaimIndexRouteImport } from './routes/claim.index'
import { Route as ClaimTokenRouteImport } from './routes/claim.$token'
import { Route as CoachProfileIdRouteImport } from './routes/coach.$profileId'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsIdRouteImport } from './routes/insights.$id'
import { Route as LocaleCoachProfileIdRouteImport } from './routes/$locale/coach.$profileId'
import { Route as LocaleEventsIndexRouteImport } from './routes/$locale/events.index'
import { Route as LocaleEventsSlugRouteImport } from './routes/$locale/events.$slug'
import { Route as LocaleInsightsIndexRouteImport } from './routes/$locale/insights.index'
import { Route as LocaleInsightsIdRouteImport } from './routes/$locale/insights.$id'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as StaffArticlesIndexRouteImport } from './routes/_staff/articles.index'
import { Route as StaffArticlesIdRouteImport } from './routes/_staff/articles.$id'
import { Route as StaffArticlesCategoriesRouteImport } from './routes/_staff/articles.categories'
import { Route as StaffArticlesNewRouteImport } from './routes/_staff/articles.new'
import { Route as StaffMembersIndexRouteImport } from './routes/_staff/members.index'
import { Route as StaffMembersIdRouteImport } from './routes/_staff/members.$id'
import { Route as ApiPublicMemberSyncRouteImport } from './routes/api/public/member-sync'
import { Route as StaffManageEventsIndexRouteImport } from './routes/_staff/manage.events.index'
import { Route as StaffManageEventsIdRouteImport } from './routes/_staff/manage.events.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRouteRoute = MemberRouteRouteImport.update({
  id: '/_member',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRouteRoute = StaffRouteRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FindACoachRoute = FindACoachRouteImport.update({
  id: '/find-a-coach',
  path: '/find-a-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCoachesRoute = ForCoachesRouteImport.update({
  id: '/for-coaches',
  path: '/for-coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const ForOrganisationsRoute = ForOrganisationsRouteImport.update({
  id: '/for-organisations',
  path: '/for-organisations',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NoAccessRoute = NoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignInRoute = StaffSignInRouteImport.update({
  id: '/staff-sign-in',
  path: '/staff-sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleFindACoachRoute = LocaleFindACoachRouteImport.update({
  id: '/find-a-coach',
  path: '/find-a-coach',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleForCoachesRoute = LocaleForCoachesRouteImport.update({
  id: '/for-coaches',
  path: '/for-coaches',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleForOrganisationsRoute = LocaleForOrganisationsRouteImport.update({
  id: '/for-organisations',
  path: '/for-organisations',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleImprintRoute = LocaleImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleInsightsRoute = LocaleInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePrivacyRoute = LocalePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const MemberMyProfileRoute = MemberMyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => MemberRouteRoute,
} as any)
const StaffArticlesRoute = StaffArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffCoachFinderRoute = StaffCoachFinderRouteImport.update({
  id: '/coach-finder',
  path: '/coach-finder',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffIntegrationRoute = StaffIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffRolesRoute = StaffRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffVocabulariesRoute = StaffVocabulariesRouteImport.update({
  id: '/vocabularies',
  path: '/vocabularies',
  getParentRoute: () => StaffRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ClaimIndexRoute = ClaimIndexRouteImport.update({
  id: '/claim/',
  path: '/claim/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimTokenRoute = ClaimTokenRouteImport.update({
  id: '/claim/$token',
  path: '/claim/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachProfileIdRoute = CoachProfileIdRouteImport.update({
  id: '/coach/$profileId',
  path: '/coach/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsightsRoute,
} as any)
const InsightsIdRoute = InsightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InsightsRoute,
} as any)
const LocaleCoachProfileIdRoute = LocaleCoachProfileIdRouteImport.update({
  id: '/coach/$profileId',
  path: '/coach/$profileId',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleEventsIndexRoute = LocaleEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleEventsSlugRoute = LocaleEventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleInsightsIndexRoute = LocaleInsightsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleInsightsRoute,
} as any)
const LocaleInsightsIdRoute = LocaleInsightsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LocaleInsightsRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const StaffArticlesIndexRoute = StaffArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffArticlesRoute,
} as any)
const StaffArticlesIdRoute = StaffArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StaffArticlesRoute,
} as any)
const StaffArticlesCategoriesRoute = StaffArticlesCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => StaffArticlesRoute,
} as any)
const StaffArticlesNewRoute = StaffArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StaffArticlesRoute,
} as any)
const StaffMembersIndexRoute = StaffMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffMembersIdRoute = StaffMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => StaffRouteRoute,
} as any)
const ApiPublicMemberSyncRoute = ApiPublicMemberSyncRouteImport.update({
  id: '/api/public/member-sync',
  path: '/api/public/member-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffManageEventsIndexRoute = StaffManageEventsIndexRouteImport.update({
  id: '/manage/events/',
  path: '/manage/events/',
  getParentRoute: () => StaffRouteRoute,
} as any)
const StaffManageEventsIdRoute = StaffManageEventsIdRouteImport.update({
  id: '/manage/events/$id',
  path: '/manage/events/$id',
  getParentRoute: () => StaffRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/find-a-coach': typeof FindACoachRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/imprint': typeof ImprintRoute
  '/insights': typeof InsightsRouteWithChildren
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-sign-in': typeof StaffSignInRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/find-a-coach': typeof LocaleFindACoachRoute
  '/$locale/for-coaches': typeof LocaleForCoachesRoute
  '/$locale/for-organisations': typeof LocaleForOrganisationsRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale/insights': typeof LocaleInsightsRouteWithChildren
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/my-profile': typeof MemberMyProfileRoute
  '/articles': typeof StaffArticlesRouteWithChildren
  '/coach-finder': typeof StaffCoachFinderRoute
  '/integration': typeof StaffIntegrationRoute
  '/roles': typeof StaffRolesRoute
  '/vocabularies': typeof StaffVocabulariesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/coach/$profileId': typeof CoachProfileIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/insights/$id': typeof InsightsIdRoute
  '/$locale/': typeof LocaleIndexRoute
  '/claim/': typeof ClaimIndexRoute
  '/events/': typeof EventsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/$locale/coach/$profileId': typeof LocaleCoachProfileIdRoute
  '/$locale/events/$slug': typeof LocaleEventsSlugRoute
  '/$locale/insights/$id': typeof LocaleInsightsIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/articles/$id': typeof StaffArticlesIdRoute
  '/articles/categories': typeof StaffArticlesCategoriesRoute
  '/articles/new': typeof StaffArticlesNewRoute
  '/members/$id': typeof StaffMembersIdRoute
  '/api/public/member-sync': typeof ApiPublicMemberSyncRoute
  '/$locale/events/': typeof LocaleEventsIndexRoute
  '/$locale/insights/': typeof LocaleInsightsIndexRoute
  '/articles/': typeof StaffArticlesIndexRoute
  '/members/': typeof StaffMembersIndexRoute
  '/manage/events/$id': typeof StaffManageEventsIdRoute
  '/manage/events/': typeof StaffManageEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/find-a-coach': typeof FindACoachRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/imprint': typeof ImprintRoute
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-sign-in': typeof StaffSignInRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/find-a-coach': typeof LocaleFindACoachRoute
  '/$locale/for-coaches': typeof LocaleForCoachesRoute
  '/$locale/for-organisations': typeof LocaleForOrganisationsRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/my-profile': typeof MemberMyProfileRoute
  '/coach-finder': typeof StaffCoachFinderRoute
  '/integration': typeof StaffIntegrationRoute
  '/roles': typeof StaffRolesRoute
  '/vocabularies': typeof StaffVocabulariesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/coach/$profileId': typeof CoachProfileIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/insights/$id': typeof InsightsIdRoute
  '/$locale': typeof LocaleIndexRoute
  '/claim': typeof ClaimIndexRoute
  '/events': typeof EventsIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/$locale/coach/$profileId': typeof LocaleCoachProfileIdRoute
  '/$locale/events/$slug': typeof LocaleEventsSlugRoute
  '/$locale/insights/$id': typeof LocaleInsightsIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/articles/$id': typeof StaffArticlesIdRoute
  '/articles/categories': typeof StaffArticlesCategoriesRoute
  '/articles/new': typeof StaffArticlesNewRoute
  '/members/$id': typeof StaffMembersIdRoute
  '/api/public/member-sync': typeof ApiPublicMemberSyncRoute
  '/$locale/events': typeof LocaleEventsIndexRoute
  '/$locale/insights': typeof LocaleInsightsIndexRoute
  '/articles': typeof StaffArticlesIndexRoute
  '/members': typeof StaffMembersIndexRoute
  '/manage/events/$id': typeof StaffManageEventsIdRoute
  '/manage/events': typeof StaffManageEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/_member': typeof MemberRouteRouteWithChildren
  '/_staff': typeof StaffRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRouteWithChildren
  '/find-a-coach': typeof FindACoachRoute
  '/for-coaches': typeof ForCoachesRoute
  '/for-organisations': typeof ForOrganisationsRoute
  '/imprint': typeof ImprintRoute
  '/insights': typeof InsightsRouteWithChildren
  '/mcp': typeof McpRoute
  '/no-access': typeof NoAccessRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/staff-sign-in': typeof StaffSignInRoute
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/find-a-coach': typeof LocaleFindACoachRoute
  '/$locale/for-coaches': typeof LocaleForCoachesRoute
  '/$locale/for-organisations': typeof LocaleForOrganisationsRoute
  '/$locale/imprint': typeof LocaleImprintRoute
  '/$locale/insights': typeof LocaleInsightsRouteWithChildren
  '/$locale/privacy': typeof LocalePrivacyRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_member/my-profile': typeof MemberMyProfileRoute
  '/_staff/articles': typeof StaffArticlesRouteWithChildren
  '/_staff/coach-finder': typeof StaffCoachFinderRoute
  '/_staff/integration': typeof StaffIntegrationRoute
  '/_staff/roles': typeof StaffRolesRoute
  '/_staff/vocabularies': typeof StaffVocabulariesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/claim/$token': typeof ClaimTokenRoute
  '/coach/$profileId': typeof CoachProfileIdRoute
  '/events/$slug': typeof EventsSlugRoute
  '/insights/$id': typeof InsightsIdRoute
  '/$locale/': typeof LocaleIndexRoute
  '/claim/': typeof ClaimIndexRoute
  '/events/': typeof EventsIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/$locale/coach/$profileId': typeof LocaleCoachProfileIdRoute
  '/$locale/events/$slug': typeof LocaleEventsSlugRoute
  '/$locale/insights/$id': typeof LocaleInsightsIdRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_staff/articles/$id': typeof StaffArticlesIdRoute
  '/_staff/articles/categories': typeof StaffArticlesCategoriesRoute
  '/_staff/articles/new': typeof StaffArticlesNewRoute
  '/_staff/members/$id': typeof StaffMembersIdRoute
  '/api/public/member-sync': typeof ApiPublicMemberSyncRoute
  '/$locale/events/': typeof LocaleEventsIndexRoute
  '/$locale/insights/': typeof LocaleInsightsIndexRoute
  '/_staff/articles/': typeof StaffArticlesIndexRoute
  '/_staff/members/': typeof StaffMembersIndexRoute
  '/_staff/manage/events/$id': typeof StaffManageEventsIdRoute
  '/_staff/manage/events/': typeof StaffManageEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/about'
    | '/auth'
    | '/find-a-coach'
    | '/for-coaches'
    | '/for-organisations'
    | '/imprint'
    | '/insights'
    | '/mcp'
    | '/no-access'
    | '/privacy'
    | '/sitemap.xml'
    | '/staff-sign-in'
    | '/$locale/about'
    | '/$locale/find-a-coach'
    | '/$locale/for-coaches'
    | '/$locale/for-organisations'
    | '/$locale/imprint'
    | '/$locale/insights'
    | '/$locale/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/my-profile'
    | '/articles'
    | '/coach-finder'
    | '/integration'
    | '/roles'
    | '/vocabularies'
    | '/auth/callback'
    | '/claim/$token'
    | '/coach/$profileId'
    | '/events/$slug'
    | '/insights/$id'
    | '/$locale/'
    | '/claim/'
    | '/events/'
    | '/insights/'
    | '/$locale/coach/$profileId'
    | '/$locale/events/$slug'
    | '/$locale/insights/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/articles/$id'
    | '/articles/categories'
    | '/articles/new'
    | '/members/$id'
    | '/api/public/member-sync'
    | '/$locale/events/'
    | '/$locale/insights/'
    | '/articles/'
    | '/members/'
    | '/manage/events/$id'
    | '/manage/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/find-a-coach'
    | '/for-coaches'
    | '/for-organisations'
    | '/imprint'
    | '/mcp'
    | '/no-access'
    | '/privacy'
    | '/sitemap.xml'
    | '/staff-sign-in'
    | '/$locale/about'
    | '/$locale/find-a-coach'
    | '/$locale/for-coaches'
    | '/$locale/for-organisations'
    | '/$locale/imprint'
    | '/$locale/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/my-profile'
    | '/coach-finder'
    | '/integration'
    | '/roles'
    | '/vocabularies'
    | '/auth/callback'
    | '/claim/$token'
    | '/coach/$profileId'
    | '/events/$slug'
    | '/insights/$id'
    | '/$locale'
    | '/claim'
    | '/events'
    | '/insights'
    | '/$locale/coach/$profileId'
    | '/$locale/events/$slug'
    | '/$locale/insights/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/articles/$id'
    | '/articles/categories'
    | '/articles/new'
    | '/members/$id'
    | '/api/public/member-sync'
    | '/$locale/events'
    | '/$locale/insights'
    | '/articles'
    | '/members'
    | '/manage/events/$id'
    | '/manage/events'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/_member'
    | '/_staff'
    | '/about'
    | '/auth'
    | '/find-a-coach'
    | '/for-coaches'
    | '/for-organisations'
    | '/imprint'
    | '/insights'
    | '/mcp'
    | '/no-access'
    | '/privacy'
    | '/sitemap.xml'
    | '/staff-sign-in'
    | '/$locale/about'
    | '/$locale/find-a-coach'
    | '/$locale/for-coaches'
    | '/$locale/for-organisations'
    | '/$locale/imprint'
    | '/$locale/insights'
    | '/$locale/privacy'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_member/my-profile'
    | '/_staff/articles'
    | '/_staff/coach-finder'
    | '/_staff/integration'
    | '/_staff/roles'
    | '/_staff/vocabularies'
    | '/auth/callback'
    | '/claim/$token'
    | '/coach/$profileId'
    | '/events/$slug'
    | '/insights/$id'
    | '/$locale/'
    | '/claim/'
    | '/events/'
    | '/insights/'
    | '/$locale/coach/$profileId'
    | '/$locale/events/$slug'
    | '/$locale/insights/$id'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_staff/articles/$id'
    | '/_staff/articles/categories'
    | '/_staff/articles/new'
    | '/_staff/members/$id'
    | '/api/public/member-sync'
    | '/$locale/events/'
    | '/$locale/insights/'
    | '/_staff/articles/'
    | '/_staff/members/'
    | '/_staff/manage/events/$id'
    | '/_staff/manage/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  MemberRouteRoute: typeof MemberRouteRouteWithChildren
  StaffRouteRoute: typeof StaffRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRouteWithChildren
  FindACoachRoute: typeof FindACoachRoute
  ForCoachesRoute: typeof ForCoachesRoute
  ForOrganisationsRoute: typeof ForOrganisationsRoute
  ImprintRoute: typeof ImprintRoute
  InsightsRoute: typeof InsightsRouteWithChildren
  McpRoute: typeof McpRoute
  NoAccessRoute: typeof NoAccessRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StaffSignInRoute: typeof StaffSignInRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ClaimTokenRoute: typeof ClaimTokenRoute
  CoachProfileIdRoute: typeof CoachProfileIdRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ClaimIndexRoute: typeof ClaimIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicMemberSyncRoute: typeof ApiPublicMemberSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member': {
      id: '/_member'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MemberRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-coach': {
      id: '/find-a-coach'
      path: '/find-a-coach'
      fullPath: '/find-a-coach'
      preLoaderRoute: typeof FindACoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-coaches': {
      id: '/for-coaches'
      path: '/for-coaches'
      fullPath: '/for-coaches'
      preLoaderRoute: typeof ForCoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-organisations': {
      id: '/for-organisations'
      path: '/for-organisations'
      fullPath: '/for-organisations'
      preLoaderRoute: typeof ForOrganisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-access': {
      id: '/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof NoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-sign-in': {
      id: '/staff-sign-in'
      path: '/staff-sign-in'
      fullPath: '/staff-sign-in'
      preLoaderRoute: typeof StaffSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/find-a-coach': {
      id: '/$locale/find-a-coach'
      path: '/find-a-coach'
      fullPath: '/$locale/find-a-coach'
      preLoaderRoute: typeof LocaleFindACoachRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/for-coaches': {
      id: '/$locale/for-coaches'
      path: '/for-coaches'
      fullPath: '/$locale/for-coaches'
      preLoaderRoute: typeof LocaleForCoachesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/for-organisations': {
      id: '/$locale/for-organisations'
      path: '/for-organisations'
      fullPath: '/$locale/for-organisations'
      preLoaderRoute: typeof LocaleForOrganisationsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/imprint': {
      id: '/$locale/imprint'
      path: '/imprint'
      fullPath: '/$locale/imprint'
      preLoaderRoute: typeof LocaleImprintRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/insights': {
      id: '/$locale/insights'
      path: '/insights'
      fullPath: '/$locale/insights'
      preLoaderRoute: typeof LocaleInsightsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/privacy': {
      id: '/$locale/privacy'
      path: '/privacy'
      fullPath: '/$locale/privacy'
      preLoaderRoute: typeof LocalePrivacyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_member/my-profile': {
      id: '/_member/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MemberMyProfileRouteImport
      parentRoute: typeof MemberRouteRoute
    }
    '/_staff/articles': {
      id: '/_staff/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof StaffArticlesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/coach-finder': {
      id: '/_staff/coach-finder'
      path: '/coach-finder'
      fullPath: '/coach-finder'
      preLoaderRoute: typeof StaffCoachFinderRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/integration': {
      id: '/_staff/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof StaffIntegrationRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/roles': {
      id: '/_staff/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof StaffRolesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/vocabularies': {
      id: '/_staff/vocabularies'
      path: '/vocabularies'
      fullPath: '/vocabularies'
      preLoaderRoute: typeof StaffVocabulariesRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/claim/': {
      id: '/claim/'
      path: '/claim'
      fullPath: '/claim/'
      preLoaderRoute: typeof ClaimIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$token': {
      id: '/claim/$token'
      path: '/claim/$token'
      fullPath: '/claim/$token'
      preLoaderRoute: typeof ClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/$profileId': {
      id: '/coach/$profileId'
      path: '/coach/$profileId'
      fullPath: '/coach/$profileId'
      preLoaderRoute: typeof CoachProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/insights/$id': {
      id: '/insights/$id'
      path: '/$id'
      fullPath: '/insights/$id'
      preLoaderRoute: typeof InsightsIdRouteImport
      parentRoute: typeof InsightsRoute
    }
    '/$locale/coach/$profileId': {
      id: '/$locale/coach/$profileId'
      path: '/coach/$profileId'
      fullPath: '/$locale/coach/$profileId'
      preLoaderRoute: typeof LocaleCoachProfileIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/events/': {
      id: '/$locale/events/'
      path: '/events'
      fullPath: '/$locale/events/'
      preLoaderRoute: typeof LocaleEventsIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/events/$slug': {
      id: '/$locale/events/$slug'
      path: '/events/$slug'
      fullPath: '/$locale/events/$slug'
      preLoaderRoute: typeof LocaleEventsSlugRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/insights/': {
      id: '/$locale/insights/'
      path: '/'
      fullPath: '/$locale/insights/'
      preLoaderRoute: typeof LocaleInsightsIndexRouteImport
      parentRoute: typeof LocaleInsightsRoute
    }
    '/$locale/insights/$id': {
      id: '/$locale/insights/$id'
      path: '/$id'
      fullPath: '/$locale/insights/$id'
      preLoaderRoute: typeof LocaleInsightsIdRouteImport
      parentRoute: typeof LocaleInsightsRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/articles/': {
      id: '/_staff/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof StaffArticlesIndexRouteImport
      parentRoute: typeof StaffArticlesRoute
    }
    '/_staff/articles/$id': {
      id: '/_staff/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof StaffArticlesIdRouteImport
      parentRoute: typeof StaffArticlesRoute
    }
    '/_staff/articles/categories': {
      id: '/_staff/articles/categories'
      path: '/categories'
      fullPath: '/articles/categories'
      preLoaderRoute: typeof StaffArticlesCategoriesRouteImport
      parentRoute: typeof StaffArticlesRoute
    }
    '/_staff/articles/new': {
      id: '/_staff/articles/new'
      path: '/new'
      fullPath: '/articles/new'
      preLoaderRoute: typeof StaffArticlesNewRouteImport
      parentRoute: typeof StaffArticlesRoute
    }
    '/_staff/members/': {
      id: '/_staff/members/'
      path: '/members'
      fullPath: '/members/'
      preLoaderRoute: typeof StaffMembersIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/members/$id': {
      id: '/_staff/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof StaffMembersIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/api/public/member-sync': {
      id: '/api/public/member-sync'
      path: '/api/public/member-sync'
      fullPath: '/api/public/member-sync'
      preLoaderRoute: typeof ApiPublicMemberSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/manage/events/': {
      id: '/_staff/manage/events/'
      path: '/manage/events'
      fullPath: '/manage/events/'
      preLoaderRoute: typeof StaffManageEventsIndexRouteImport
      parentRoute: typeof StaffRouteRoute
    }
    '/_staff/manage/events/$id': {
      id: '/_staff/manage/events/$id'
      path: '/manage/events/$id'
      fullPath: '/manage/events/$id'
      preLoaderRoute: typeof StaffManageEventsIdRouteImport
      parentRoute: typeof StaffRouteRoute
    }
  }
}

interface LocaleInsightsRouteChildren {
  LocaleInsightsIdRoute: typeof LocaleInsightsIdRoute
  LocaleInsightsIndexRoute: typeof LocaleInsightsIndexRoute
}

const LocaleInsightsRouteChildren: LocaleInsightsRouteChildren = {
  LocaleInsightsIdRoute: LocaleInsightsIdRoute,
  LocaleInsightsIndexRoute: LocaleInsightsIndexRoute,
}

const LocaleInsightsRouteWithChildren = LocaleInsightsRoute._addFileChildren(
  LocaleInsightsRouteChildren,
)

interface LocaleRouteRouteChildren {
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleFindACoachRoute: typeof LocaleFindACoachRoute
  LocaleForCoachesRoute: typeof LocaleForCoachesRoute
  LocaleForOrganisationsRoute: typeof LocaleForOrganisationsRoute
  LocaleImprintRoute: typeof LocaleImprintRoute
  LocaleInsightsRoute: typeof LocaleInsightsRouteWithChildren
  LocalePrivacyRoute: typeof LocalePrivacyRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleCoachProfileIdRoute: typeof LocaleCoachProfileIdRoute
  LocaleEventsSlugRoute: typeof LocaleEventsSlugRoute
  LocaleEventsIndexRoute: typeof LocaleEventsIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleFindACoachRoute: LocaleFindACoachRoute,
  LocaleForCoachesRoute: LocaleForCoachesRoute,
  LocaleForOrganisationsRoute: LocaleForOrganisationsRoute,
  LocaleImprintRoute: LocaleImprintRoute,
  LocaleInsightsRoute: LocaleInsightsRouteWithChildren,
  LocalePrivacyRoute: LocalePrivacyRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleCoachProfileIdRoute: LocaleCoachProfileIdRoute,
  LocaleEventsSlugRoute: LocaleEventsSlugRoute,
  LocaleEventsIndexRoute: LocaleEventsIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

interface MemberRouteRouteChildren {
  MemberMyProfileRoute: typeof MemberMyProfileRoute
}

const MemberRouteRouteChildren: MemberRouteRouteChildren = {
  MemberMyProfileRoute: MemberMyProfileRoute,
}

const MemberRouteRouteWithChildren = MemberRouteRoute._addFileChildren(
  MemberRouteRouteChildren,
)

interface StaffArticlesRouteChildren {
  StaffArticlesIdRoute: typeof StaffArticlesIdRoute
  StaffArticlesCategoriesRoute: typeof StaffArticlesCategoriesRoute
  StaffArticlesNewRoute: typeof StaffArticlesNewRoute
  StaffArticlesIndexRoute: typeof StaffArticlesIndexRoute
}

const StaffArticlesRouteChildren: StaffArticlesRouteChildren = {
  StaffArticlesIdRoute: StaffArticlesIdRoute,
  StaffArticlesCategoriesRoute: StaffArticlesCategoriesRoute,
  StaffArticlesNewRoute: StaffArticlesNewRoute,
  StaffArticlesIndexRoute: StaffArticlesIndexRoute,
}

const StaffArticlesRouteWithChildren = StaffArticlesRoute._addFileChildren(
  StaffArticlesRouteChildren,
)

interface StaffRouteRouteChildren {
  StaffArticlesRoute: typeof StaffArticlesRouteWithChildren
  StaffCoachFinderRoute: typeof StaffCoachFinderRoute
  StaffIntegrationRoute: typeof StaffIntegrationRoute
  StaffRolesRoute: typeof StaffRolesRoute
  StaffVocabulariesRoute: typeof StaffVocabulariesRoute
  StaffMembersIdRoute: typeof StaffMembersIdRoute
  StaffMembersIndexRoute: typeof StaffMembersIndexRoute
  StaffManageEventsIdRoute: typeof StaffManageEventsIdRoute
  StaffManageEventsIndexRoute: typeof StaffManageEventsIndexRoute
}

const StaffRouteRouteChildren: StaffRouteRouteChildren = {
  StaffArticlesRoute: StaffArticlesRouteWithChildren,
  StaffCoachFinderRoute: StaffCoachFinderRoute,
  StaffIntegrationRoute: StaffIntegrationRoute,
  StaffRolesRoute: StaffRolesRoute,
  StaffVocabulariesRoute: StaffVocabulariesRoute,
  StaffMembersIdRoute: StaffMembersIdRoute,
  StaffMembersIndexRoute: StaffMembersIndexRoute,
  StaffManageEventsIdRoute: StaffManageEventsIdRoute,
  StaffManageEventsIndexRoute: StaffManageEventsIndexRoute,
}

const StaffRouteRouteWithChildren = StaffRouteRoute._addFileChildren(
  StaffRouteRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface InsightsRouteChildren {
  InsightsIdRoute: typeof InsightsIdRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
}

const InsightsRouteChildren: InsightsRouteChildren = {
  InsightsIdRoute: InsightsIdRoute,
  InsightsIndexRoute: InsightsIndexRoute,
}

const InsightsRouteWithChildren = InsightsRoute._addFileChildren(
  InsightsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  MemberRouteRoute: MemberRouteRouteWithChildren,
  StaffRouteRoute: StaffRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRouteWithChildren,
  FindACoachRoute: FindACoachRoute,
  ForCoachesRoute: ForCoachesRoute,
  ForOrganisationsRoute: ForOrganisationsRoute,
  ImprintRoute: ImprintRoute,
  InsightsRoute: InsightsRouteWithChildren,
  McpRoute: McpRoute,
  NoAccessRoute: NoAccessRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StaffSignInRoute: StaffSignInRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ClaimTokenRoute: ClaimTokenRoute,
  CoachProfileIdRoute: CoachProfileIdRoute,
  EventsSlugRoute: EventsSlugRoute,
  ClaimIndexRoute: ClaimIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicMemberSyncRoute: ApiPublicMemberSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
